//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuGet {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PsdResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PsdResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NuGet.PsdResources", typeof(PsdResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API key to be used when connecting to an authenticated source..
        /// </summary>
        internal static string DiscoverCommandApiKeyDescription {
            get {
                return ResourceManager.GetString("DiscoverCommandApiKeyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both UserName and Password must be specified..
        /// </summary>
        internal static string DiscoverCommandCredentialsRequired {
            get {
                return ResourceManager.GetString("DiscoverCommandCredentialsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provides the ability to discover sources from a given URL and register them in  %AppData%\NuGet\NuGet.config.
        /// </summary>
        internal static string DiscoverCommandDescription {
            get {
                return ResourceManager.GetString("DiscoverCommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password to be used when connecting to an authenticated source..
        /// </summary>
        internal static string DiscoverCommandPasswordDescription {
            get {
                return ResourceManager.GetString("DiscoverCommandPasswordDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} discovered package sources have been registered..
        /// </summary>
        internal static string DiscoverCommandSuccessful {
            get {
                return ResourceManager.GetString("DiscoverCommandSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL from which sources should be discovered..
        /// </summary>
        internal static string DiscoverCommandUrlDescription {
            get {
                return ResourceManager.GetString("DiscoverCommandUrlDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The URL specified cannot be empty. Please provide a valid URL..
        /// </summary>
        internal static string DiscoverCommandUrlRequired {
            get {
                return ResourceManager.GetString("DiscoverCommandUrlRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -Url [url].
        /// </summary>
        internal static string DiscoverCommandUsageSummary {
            get {
                return ResourceManager.GetString("DiscoverCommandUsageSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username to be used when connecting to an authenticated source..
        /// </summary>
        internal static string DiscoverCommandUserNameDescription {
            get {
                return ResourceManager.GetString("DiscoverCommandUserNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The URL specified is invalid. Please provide a valid URL..
        /// </summary>
        internal static string DiscoverCommandValidUrlRequired {
            get {
                return ResourceManager.GetString("DiscoverCommandValidUrlRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property SourceProvider is null..
        /// </summary>
        internal static string Error_SourceProviderIsNull {
            get {
                return ResourceManager.GetString("Error_SourceProviderIsNull", resourceCulture);
            }
        }
    }
}
